[package]
name = "app-launcher"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyrun-plugin = "0.1.0"
abi_stable = "0.11.3"
fuzzy-matcher = "0.3.7"
ron = "0.8.1"
serde = { version = "1.0.219", features = ["derive"] }
once_cell = "1.21.3"
